# `<NuxtErrorBoundary>`

Nuxt 内置了 `<NuxtErrorBoundary>` 组件来处理它内部插槽在客户端时发生的错误。它是通过Vue的钩子函数 [`onErrorCaptured` hook.](https://vuejs.org/api/composition-api-lifecycle.html#onerrorcaptured)实现的。

## 事件

- **`@error`**: 当默认插槽内的组件抛出错误是触发这个事件。

  ```vue
  <template>
    <NuxtErrorBoundary @error="logSomeError">
      <!-- ... -->
    </NuxtErrorBoundary>
  </template>
  ```

## 插槽

- **#error**: 设置发生错误时的内容展示。

  ```vue
    <template>
      <NuxtErrorBoundary>
        <!-- ... -->
        <template #error="{ error }">
          <p>An error occurred: {{ error }}</p>
        </template>
      </NuxtErrorBoundary>
    </template>
  ```

::ReadMore{link="/guide/features/error-handling"}
::
